# Generated by Django 5.1.3 on 2024-12-03 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssh_cruise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("invoice_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("room_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("package_cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "ssh_invoice",
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                ("package_id", models.AutoField(primary_key=True, serialize=False)),
                ("package_name", models.CharField(max_length=30)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "ssh_packages",
            },
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                ("passenger_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField()),
                ("street_address", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
                ("zip_code", models.CharField(max_length=6)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
            options={
                "db_table": "ssh_passenger",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("payment_date", models.DateField(auto_now_add=True)),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("payment_method", models.CharField(max_length=30)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ssh_cruise.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "ssh_payment",
            },
        ),
        migrations.CreateModel(
            name="Side",
            fields=[
                ("side_id", models.AutoField(primary_key=True, serialize=False)),
                ("side_name", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "ssh_sides",
            },
        ),
        migrations.CreateModel(
            name="Stateroom",
            fields=[
                ("stateroom_id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=30)),
                ("size", models.IntegerField()),
            ],
            options={
                "db_table": "ssh_stateroom",
            },
        ),
        migrations.DeleteModel(
            name="Port",
        ),
    ]
