# Generated by Django 5.1.3 on 2024-12-03 23:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ssh_cruise",
            "0002_invoice_package_passenger_payment_side_stateroom_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="package",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="passenger",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="side",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="stateroom",
            options={"managed": False},
        ),
    ]
