# Generated by Django 4.2.15 on 2024-12-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssh_cruise', '0003_alter_invoice_options_alter_package_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={},
        ),
        migrations.AlterModelOptions(
            name='side',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stateroom',
            options={},
        ),
    ]
